### ISSUE TITLE
Document notification templates

### ISSUE THREAD

**Issue by davralin** [drone-plugins/drone-matrix#16]
Is there any documentation regarding notification templates?

Out of the box, I get something like `Build failure project/repo#92aebb2c (master) by` (notice the full stop after `by`).

And I'd also like to adjust the feedback in the notifications a bit.

Over at discourse, I stumbled upon the following unanswered questions, so that's why I came here.

https://discourse.drone.io/t/matrix-plugin-multiline-templates/6810

https://discourse.drone.io/t/add-documentation-on-template-syntax/5707

**Comment by ptman** [comment]
Template seems to be defined here: https://github.com/drone-plugins/drone-matrix/blob/c9534cf70ad2712b1fd5babbf6d2ce12a5951530/main.go#L56

**Comment by tboerger** [comment]
As the templating works the same way we need to add it on a central place to the plugin registry, still not done :(
