### ISSUE TITLE
Update image to support TLS 1.3

### ISSUE THREAD

**Issue by r3pek** [drone-plugins/drone-matrix#17]
What the tittle says. Right now, if connection to a TLS1.3 only server, we get this message:

`2020/11/05 22:56:49 failed to authenticate user: Post https://xxxxxxxxx/_matrix/client/r0/login: remote error: tls: protocol version not supported`

**Comment by tboerger** [comment]
Not sure what needs to be done here, I guess an updated Go version to compile the plugin?

**Comment by r3pek** [comment]
Yeah, I think you need at least Go 1.12 (not sure which is the latest version)

**Comment by donny-dont** [comment]
Please do a local build of https://github.com/drone-plugins/drone-matrix/pull/18 and see if this solves your problem. I don't use matrix so I can't verify it works.

**Comment by r3pek** [comment]
@donny-dont not really sure how i can test this :-/
btw, i guess all images have this problem (just hit it with the docker plugin too). should i open an issue on everyone?

**Comment by donny-dont** [comment]
You would need to build the executable and see if it connects to your server.

```
go build ./cmd/drone-matrix
```

Will make an exe. You can then run `./drone-matrix --help` to get a list of options. You should see options that correspond to the settings values. Run it and see if it works.

With the docker one things might be tricky for you https://github.com/drone-plugins/drone-docker/issues/244 so you should probably not use TLS 1.3 exclusively if you have a local registry. But yea you can open the bug.

**Comment by r3pek** [comment]
Tested it and it works (built with go 1.14.10)

I don't have a private registry, so, it's only the "connecting to" part i'm worried. ;)

**Comment by tboerger** [comment]
This should be fixed by https://github.com/drone-plugins/drone-matrix/pull/18
